#!/bin/bash

pushpull=$1
gitdirs=($HOME/Coding/Gale $HOME/Coding/dotfiles/ $HOME/.vim/)



if [ "$pushpull" = "pull" ]
then 
    #Now git
    for tdir in ${gitdirs[*]};
    do 
        cd $tdir;
        git pull;
    done
elif [ "$pushpull" = "push" ]
then
    #Now git
    for tdir in ${gitdirs[*]};
    do 
        cd $tdir;
        git commit -a -m "Standard commit fired from the brain";
        git push;
    done
else
    echo 'ERROR: Unrecognised option.'
    echo 'Please submit "push" or "pull" as an option.'
fi

